require("focus").setup({
        enable = false,
        autoresize = false,
	excluded_filetypes = {
		"dashboard",
		"toggleterm",
		"vista",
		"vista_kind",
		"toggleterm",
		"NvimTree",
		"dapui_scopes",
		"dapui_breakpoints",
		"dapui_stacks",
		"dapui_watches",
		"dap-repl",
		"help",
		"terminal",
		"packer",
		"TelescopePrompt",
		"lsp-installer",
		"lspinfo",
		"calendar",
                "peek",
	},
	excluded_buftypes = {
		"help",
		"terminal",
		"lsp-installer",
		"lspinfo",
		"TelescopePrompt",
		"nofile",
	},
})
